= Perfective ESLint Config for React

`@perfective/eslint-config-react` provides
a https://eslint.org/docs/latest/developer-guide/shareable-configs[shareable ESLint configuration]
for https://reactjs.org[React] development.

`@perfective/eslint-config-react` adds the following ESLint plugins to the
`link:https://www.npmjs.com/package/@perfective/eslint-config[@perfective/eslint-config]` configuration:

* `link:https://github.com/jsx-eslint/eslint-plugin-react[eslint-plugin-react]`;
* `link:https://www.npmjs.com/package/eslint-plugin-react-hooks[eslint-plugin-react-hooks]`;
* `link:https://github.com/cvazac/eslint-plugin-react-perf[eslint-plugin-react-perf]`;
* `link:https://github.com/jsx-eslint/eslint-plugin-jsx-a11y[eslint-plugin-jsx-a11y]`.


== Setup

. Require `@perfective/eslint-config-react`:
+
[source,bash]
----
npm install --save-dev @perfective/eslint-config-react
----
+
Required peer dependencies are installed automatically.
+
. Import `perfectiveEslintReactConfig` to `eslint.config.js`:
+
[source,javascript]
----
import { perfectiveEslintReactConfig } from '@perfective/eslint-config-react';

export default perfectiveEslintReactConfig();
----
+
. _Optional_ Install optional peer dependencies to add tool-specific linting rules.
+
[source,bash]
----
npm install --save-dev \
    eslint-plugin-cypress \
    eslint-plugin-jest \
    eslint-plugin-jest-dom \
    eslint-plugin-rxjs-x \
    eslint-plugin-testing-library
----
+
Import configurations to `eslint.config.js`.
+
[source,javascript]
----
import { perfectiveEslintReactConfig } from '@perfective/eslint-config-react';

// Optional dependencies.
import { cypressConfig } from '@perfective/eslint-config/cypress';
import { jestConfig, jestTypescriptConfig } from '@perfective/eslint-config/jest';
import { jestDomConfig } from '@perfective/eslint-config/jest-dom';
import { rxjsConfig } from '@perfective/eslint-config/rxjs';
import { testingLibraryConfig } from '@perfective/eslint-config-react/testing-library';

export default perfectiveEslintReactConfig([
    cypressConfig,
    jestConfig,
    jestTypescriptConfig,
    jestDomConfig,
    rxjsConfig,
    testingLibraryConfig,
]);
----
+
NOTE: `*.d.ts` files and `dist` directories are ignored by the configuration.
`node_modules` and dot-files are ignored by the `eslint`.
If more directories or file types need to be ignored, see the
`link:https://eslint.org/docs/latest/use/configure/ignore#the-eslintignore-file[.eslintignore]` file docs.


== Packages

The following is the list of available packages and their exports.

=== `@perfective/eslint-config-react`

* `perfectiveEslintReactConfig(configs: Linter.Config[] = []): Linter.Config[]`
— creates a list of flat configs.

=== `@perfective/eslint-config-react/typescript-eslint`

* `typescriptEslintNamingConvention(extensions: TypescriptEslintNamingConvention[] = []): TypescriptEslintNamingConvention[]`
— creates a React-compatible configuration with the given extensions
for the `@typescript-eslint/naming-convention` rule.

=== `@perfective/eslint-config-react/testing-library`

* `testingLibraryConfig(files: Glob[] = jestFiles): Linter.Config`
— creates a flat config for `eslint-plugin-testing-library` for a given list of files globs.

=== `@perfective/eslint-config-react/unicorn`

* `unicornPreventAbbreviations(replacements: UnicornPreventAbbreviationReplacements = {}, options: Partial<Pick<UnicornPreventAbbreviations, 'checkProperties'>> = {}): UnicornPreventAbbreviations`
— adds React-specific abbreviations for the `unicorn/prevent-abbreviations` rule.
